paths:
- /Users/michaelheinrich/indentconfig.yaml

onlyOneBackUp: 1

modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1 
  environments:
    DBSFinishesWithLineBreak: 1
    BeginStartsOnOwnLine: 1
    BodyStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
    EndFinishesWithLineBreak: 1
